# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/codeclimate-engine-rb/all/codeclimate-engine-rb.rbi
#
# codeclimate-engine-rb-0.4.1
module CCEngine
end
class CCEngine::Issue
  def content_hash; end
  def fingerprint_hash; end
  def remediation_points_hash; end
  def render; end
  def self.attribute(name, type = nil, options = nil); end
  def to_hash; end
  def to_json; end
  extend Virtus::ClassMethods
  extend Virtus::Extensions::AllowedWriterMethods
  include Anonymous_Module_99
  include Anonymous_Virtus_AttributeSet_98
  include Virtus::ClassInclusions::Methods
  include Virtus::InstanceMethods
  include Virtus::InstanceMethods::Constructor
  include Virtus::InstanceMethods::MassAssignment
  include Virtus::Model::Constructor
  include Virtus::Model::Core
  include Virtus::Model::MassAssignment
end
module Anonymous_Module_99
  def self.extended(object); end
  def self.included(object); end
end
module Anonymous_Virtus_AttributeSet_98
  def categories; end
  def categories=(value); end
  def check_name; end
  def check_name=(value); end
  def content; end
  def content=(value); end
  def description; end
  def description=(value); end
  def fingerprint; end
  def fingerprint=(value); end
  def location; end
  def location=(value); end
  def remediation_points; end
  def remediation_points=(value); end
end
module CCEngine::Location
end
class CCEngine::Location::LineRange
  def self.attribute(name, type = nil, options = nil); end
  def to_hash; end
  extend Virtus::ClassMethods
  extend Virtus::Extensions::AllowedWriterMethods
  include Anonymous_Module_101
  include Anonymous_Virtus_AttributeSet_100
  include Virtus::ClassInclusions::Methods
  include Virtus::InstanceMethods
  include Virtus::InstanceMethods::Constructor
  include Virtus::InstanceMethods::MassAssignment
  include Virtus::Model::Constructor
  include Virtus::Model::Core
  include Virtus::Model::MassAssignment
end
module Anonymous_Module_101
  def self.extended(object); end
  def self.included(object); end
end
module Anonymous_Virtus_AttributeSet_100
  def line_range; end
  def line_range=(value); end
  def path; end
  def path=(value); end
end
class CCEngine::Location::Position
  def self.attribute(name, type = nil, options = nil); end
  def to_hash; end
  extend Virtus::ClassMethods
  extend Virtus::Extensions::AllowedWriterMethods
  include Anonymous_Module_103
  include Anonymous_Virtus_AttributeSet_102
  include Virtus::ClassInclusions::Methods
  include Virtus::InstanceMethods
  include Virtus::InstanceMethods::Constructor
  include Virtus::InstanceMethods::MassAssignment
  include Virtus::Model::Constructor
  include Virtus::Model::Core
  include Virtus::Model::MassAssignment
end
module Anonymous_Module_103
  def self.extended(object); end
  def self.included(object); end
end
module Anonymous_Virtus_AttributeSet_102
  def end_position; end
  def end_position=(value); end
  def path; end
  def path=(value); end
  def start_position; end
  def start_position=(value); end
end
module CCEngine::Category
  def self.bug_risk; end
  def self.clarity; end
  def self.compatibility; end
  def self.complexity; end
  def self.duplication; end
  def self.security; end
  def self.style; end
end
class CCEngine::Config
  def enabled?; end
  def exclude_paths; end
  def include_paths; end
  def initialize(json_string); end
  def json_string; end
  def parsed_json; end
end
