# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-matcher/all/dry-matcher.rbi
#
# dry-matcher-0.8.3

module Dry
end
class Dry::Matcher
  def call(result, &block); end
  def cases; end
  def for(*methods); end
  def initialize(cases = nil); end
  def self.for(*match_methods, with:); end
  include Dry::Core::Constants
end
class Dry::Matcher::Case
  def call(value, patterns = nil, &block); end
  def initialize(match: nil, resolve: nil, &block); end
end
class Dry::Matcher::NonExhaustiveMatchError < StandardError
end
class Dry::Matcher::Evaluator < BasicObject
  def call; end
  def ensure_exhaustive_match; end
  def initialize(result, cases); end
  def method_missing(name, *args, &block); end
  def respond_to_missing?(name, _include_private = nil); end
end
