# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/stackprof/all/stackprof.rbi
#
# stackprof-0.2.15

module StackProf
  def self.results(*arg0); end
  def self.run(*arg0); end
  def self.running?; end
  def self.sample; end
  def self.start(*arg0); end
  def self.stop; end
end
class StackProf::Report
  def +(other); end
  def add_lines(a, b); end
  def callers_for(addr); end
  def convert_to_d3_flame_graph_format(name, stacks, depth); end
  def data; end
  def files; end
  def flamegraph_row(f, x, y, weight, addr); end
  def frames(sort_by_total = nil); end
  def initialize(data); end
  def max_samples; end
  def modeline; end
  def normalized_frames; end
  def overall_samples; end
  def print_alphabetical_flamegraph(f = nil, skip_common = nil); end
  def print_callgrind(f = nil); end
  def print_d3_flamegraph(f = nil, skip_common = nil); end
  def print_debug; end
  def print_dump(f = nil); end
  def print_file(filter, f = nil); end
  def print_files(sort_by_total = nil, limit = nil, f = nil); end
  def print_flamegraph(f, skip_common, alphabetical = nil); end
  def print_graphviz(options = nil, f = nil); end
  def print_json(f = nil); end
  def print_method(name, f = nil); end
  def print_stackcollapse; end
  def print_text(sort_by_total = nil, limit = nil, select_files = nil, reject_files = nil, select_names = nil, reject_names = nil, f = nil); end
  def print_timeline_flamegraph(f = nil, skip_common = nil); end
  def root_frames; end
  def source_display(f, file, lines, range = nil); end
  def version; end
  def walk_method(name); end
end
