# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED AND SHOULD NOT BE MANUALLY MODIFIED

require 'clean_architecture/adapters/all'
require 'clean_architecture/entities/all'
require 'clean_architecture/interfaces/all'
require 'clean_architecture/matchers/all'
require 'clean_architecture/queries/all'
require 'clean_architecture/serializers/all'
require 'clean_architecture/strategies/all'

require 'clean_architecture/types'
require 'clean_architecture/version'
