# typed: strong
# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED AND SHOULD NOT BE MANUALLY MODIFIED

require 'clean_architecture/entities/failure_details'
require 'clean_architecture/entities/targeted_parameters'
require 'clean_architecture/entities/untargeted_parameters'
