# typed: strict
# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED AND SHOULD NOT BE MANUALLY MODIFIED

require 'clean_architecture/queries/http_failure_code'
require 'clean_architecture/queries/http_success_code'
