# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED AND SHOULD NOT BE MANUALLY MODIFIED

require 'clean_architecture/serializers/html_response_from_result'
require 'clean_architecture/serializers/json_response_from_result'
require 'clean_architecture/serializers/success_collection_payload'
require 'clean_architecture/serializers/success_object_payload'
