# typed: strong
# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED AND SHOULD NOT BE MANUALLY MODIFIED

require 'clean_architecture/interfaces/authorization_parameters'
require 'clean_architecture/interfaces/base_parameters'
require 'clean_architecture/interfaces/jsonable'
require 'clean_architecture/interfaces/targeted_parameters'
require 'clean_architecture/interfaces/use_case'
require 'clean_architecture/interfaces/use_case_actor'
require 'clean_architecture/interfaces/use_case_target'
