# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ActiveSupport::ActionController::Base; end
module T::CompatibilityPatches::RecorderExtensions; end
module Types::Strict::Hash; end
module Types::Strict::Integer; end
module Types::Strict::String; end
module Types::Strict::String; end
module Types::Strict::String; end
module Types::Strict::String; end
module Types::Strict::String; end
