# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED AND SHOULD NOT BE MANUALLY MODIFIED

require 'clean_architecture/strategies/actor_gets_authorized_then_does_work'
require 'clean_architecture/strategies/with_audit_trail'
